-- =============================================================================
--  FILE         : schema.sql
--  PROJECT      : Movie Database (PostgreSQL Blueprint)
--  PURPOSE      : Authoritative, consolidated DDL describing the FINAL state
--                 of the `films` relation. Run this on a fresh database to
--                 reproduce the schema without replaying the migration history.
--  TARGET DB    : PostgreSQL 12+
--  USAGE        : psql -U <user> -d <database> -f schema.sql
-- =============================================================================


-- -----------------------------------------------------------------------------
-- DEFENSIVE RESET
-- -----------------------------------------------------------------------------
-- Drops any prior version of the table so this script is fully idempotent.
-- Remove or comment out in production deployments where data must be preserved.
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS films CASCADE;


-- -----------------------------------------------------------------------------
-- TABLE : films
-- -----------------------------------------------------------------------------
-- Catalog of films tracked by the system. `id` is a surrogate key generated by
-- an implicit SERIAL sequence. `name` is constrained UNIQUE so each title can
-- appear at most once. Metadata columns are nullable to support gradual
-- enrichment workflows (e.g., scraped backfills, manual curation).
-- -----------------------------------------------------------------------------
CREATE TABLE films (
    id              SERIAL          PRIMARY KEY,
    name            TEXT            NOT NULL,
    release_year    INTEGER         NOT NULL,
    runtime         INTEGER,
    category        VARCHAR(100),
    rating          VARCHAR(10),
    box_office      BIGINT,

    CONSTRAINT unique_film_name UNIQUE (name)
);


-- -----------------------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------------------
-- B-tree indexes on commonly filtered columns. PostgreSQL automatically indexes
-- the PRIMARY KEY and UNIQUE columns, so no separate index is required for
-- `id` or `name`.
-- -----------------------------------------------------------------------------
CREATE INDEX idx_films_release_year ON films (release_year);
CREATE INDEX idx_films_category     ON films (category);


-- -----------------------------------------------------------------------------
-- METADATA COMMENTS (visible in psql `\d+` and most GUI clients)
-- -----------------------------------------------------------------------------
COMMENT ON TABLE  films               IS 'Catalog of films tracked by the system.';
COMMENT ON COLUMN films.id            IS 'Surrogate primary key (auto-incremented).';
COMMENT ON COLUMN films.name          IS 'Film title; unique across the table.';
COMMENT ON COLUMN films.release_year  IS 'Year of the film''s public release.';
COMMENT ON COLUMN films.runtime       IS 'Runtime of the film in whole minutes.';
COMMENT ON COLUMN films.category      IS 'Primary genre classification.';
COMMENT ON COLUMN films.rating        IS 'Content rating (MPAA or regional equivalent).';
COMMENT ON COLUMN films.box_office    IS 'Worldwide lifetime gross revenue (USD).';
